version: "3"

services:
    mongo:
        image: mongo:latest
        environment: 
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: pikachu
        ports:
            - 27017:27017
        volumes:
            - data:/data/db
            - ./mongo-seed:/mongo-seed
        
volumes:
    data:

    